import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#111319",
        primary: "#4fdbc8",
        "primary-container": "#14b8a6",
        "primary-fixed": "#71f8e4",
        "primary-fixed-dim": "#4fdbc8",
        "on-primary": "#003731",
        "on-primary-container": "#00423b",
        "on-primary-fixed": "#00201c",
        "on-primary-fixed-variant": "#005048",
        secondary: "#ffb95f",
        "secondary-container": "#ee9800",
        "secondary-fixed": "#ffddb8",
        "secondary-fixed-dim": "#ffb95f",
        "on-secondary": "#472a00",
        "on-secondary-container": "#5b3800",
        "on-secondary-fixed": "#2a1700",
        "on-secondary-fixed-variant": "#653e00",
        tertiary: "#ffb3ad",
        "tertiary-container": "#ff7d76",
        "tertiary-fixed": "#ffdad7",
        "tertiary-fixed-dim": "#ffb3ad",
        "on-tertiary": "#68000a",
        "on-tertiary-container": "#7b000e",
        "on-tertiary-fixed": "#410004",
        "on-tertiary-fixed-variant": "#930013",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        background: "#111319",
        "on-background": "#e1e2ea",
        "surface-dim": "#111319",
        "surface-bright": "#36393f",
        "surface-tint": "#4fdbc8",
        "surface-variant": "#32353b",
        "surface-container-lowest": "#0b0e13",
        "surface-container-low": "#191c21",
        "surface-container": "#1d2025",
        "surface-container-high": "#272a30",
        "surface-container-highest": "#32353b",
        "on-surface": "#e1e2ea",
        "on-surface-variant": "#bbcac6",
        "inverse-surface": "#e1e2ea",
        "inverse-on-surface": "#2e3036",
        "inverse-primary": "#006b5f",
        outline: "#859490",
        "outline-variant": "#3c4947",
      },
      borderRadius: {
        DEFAULT: "0px",
        none: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        "3xl": "0px",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        body: ["var(--font-inter)", "Inter", "sans-serif"],
        label: ["var(--font-inter)", "Inter", "sans-serif"],
        mono: ["var(--font-ibm-plex-mono)", "IBM Plex Mono", "monospace"],
      },
    },
  },
  plugins: [],
};

export default config;
